
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 113
#define YY_END_OF_BUFFER 114
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[448] =
    {   0,
        0,    0,    0,    0,    0,    0,   11,   11,    5,    5,
        9,    9,  114,  112,  111,   15,  106,  112,  105,  104,
        4,   90,   92,  102,  100,   89,  101,  109,  110,   86,
       94,   93,  107,   91,  108,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   95,  112,   96,  103,   97,   99,   98,
      113,    2,    3,   11,   13,  113,    5,    8,    7,  113,
        9,  113,  111,   78,    0,    0,    0,    0,    0,    0,
       79,   80,   71,   87,   10,    1,   84,    0,   86,    0,
       70,   75,   81,   77,   82,   76,   85,   85,   85,   85,

       85,   85,   85,   85,   31,   85,   85,   36,   39,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   66,   85,   85,
       85,   83,   11,    0,    0,   14,   12,    5,    0,    6,
        5,    5,    5,    5,    5,    5,    5,    9,    0,    9,
        9,    9,    9,    9,    9,    9,    0,   72,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   87,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,

       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       88,    0,    0,    0,    0,    0,   87,   85,   85,   85,
       85,   85,   85,   85,   18,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       53,   85,   55,   85,   85,   85,   85,   85,   61,   85,
       85,   85,   85,   67,   68,   85,   85,    0,   85,   85,
       85,   85,   85,   85,   33,   16,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   74,

       85,   43,   85,   85,   47,   85,   85,   50,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   64,   85,
       85,   85,   85,   85,   85,   85,   19,   85,   85,   85,
       85,   28,   26,   85,   85,   85,   85,   85,   37,   85,
       85,   85,   85,   85,   85,   85,   85,   49,   85,   85,
       85,   85,   57,   85,   85,   85,   85,   63,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   35,   85,   85,   85,   41,   42,   85,   45,
       85,   85,   85,   85,   54,   56,   85,   85,   60,   85,
       85,   85,   85,   85,   85,   20,   23,   17,   24,   85,

       85,   85,   85,   32,   34,   38,   85,   85,   46,   48,
       51,   85,   85,   59,   62,   85,   69,   85,   22,   85,
       25,   85,   85,   85,   85,   85,   85,   85,   85,   73,
       21,   85,   85,   30,   40,   44,   85,   85,   85,   27,
       29,   52,   85,   65,   85,   58,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       17,   20,   21,   22,   22,   23,   23,   24,   25,   26,
       27,   28,   29,    1,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   41,   42,   43,   44,   45,
       46,   47,   48,   49,   50,   51,   40,   52,   40,   53,
       54,   55,   56,   57,   40,    1,   58,   59,   60,   61,

       62,   63,   64,   65,   66,   67,   40,   68,   69,   70,
       71,   72,   73,   74,   75,   76,   77,   78,   40,   79,
       40,   80,   81,   82,   83,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[84] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    4,    1,    1,
        5,    1,    1,    1,    1,    1,    6,    6,    6,    6,
        6,    6,    6,    1,    1,    1,    1,    1,    1,    6,
        6,    6,    6,    6,    6,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    1,    1,    1,    1,    6,    6,    6,
        6,    6,    6,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[462] =
    {   0,
        0,    0,    0,    0,  656,  620,   81,   82,   83,   86,
       87,   93,  622, 1087,  611, 1087,  585,   82, 1087, 1087,
       85, 1087, 1087,  600, 1087, 1087,  543,   94,  107,  109,
       95, 1087,  553,  107,  534,  105,   66,  115,   87,  127,
      146,  105,  114,   77,    0,  116,  119,   76,  131,  126,
      169,  149,  179, 1087,  514, 1087, 1087, 1087, 1087, 1087,
     1087, 1087, 1087,    0, 1087,  200,  440, 1087, 1087,  239,
      439,  310,  491, 1087,    0,  461,  231,  238,  258,  381,
     1087, 1087, 1087,  302, 1087, 1087, 1087,  309,  329,  444,
     1087, 1087, 1087, 1087, 1087, 1087,    0,  102,  147,  149,

      345,  168,  158,  233,  214,  176,  183,  195,  227,  204,
      232,  273,  240,  241,  237,  238,  264,  260,  304,  309,
      307,  309,  352,  336,  349,  319,  366,  371,  370,  375,
      378, 1087,    0,  208,  218, 1087,  418,  395,  435, 1087,
      376,  342,  320,  319,  317,  316,  307,  303,    0,  282,
      251,  249,  248,  246,  241,  238,  235, 1087,  224,  460,
      467,  483,  222,  488,  503,  214,  213,  206,  192,  161,
      150,  147,    0,  514,  495,  521,  377,  345,  386,  375,
      383,  515,  402,  399,  507,  427,  424,  515,  428,  416,
      450,  514,  495,  515,  479,  513,  522,  521,  522,  510,

      526,  509,  514,  522,  528,  524,  519,  540,  521,  569,
      542,  546,  555,  559,  564,  565,  563,  564,  566,  576,
     1087,  143,  598,  126,   92,  621,  628,  579,  586,  593,
      604,  611,  624,  627,    0,  624,  610,  612,  629,  620,
      629,  619,  626,  618,  635,  624,  629,  641,  630,  632,
      643,  638,  642,  635,  653,  642,  666,  670,  655,  672,
        0,  676,    0,  682,  683,  680,  670,  677,    0,  670,
      670,  673,  676,    0,    0,  692,  693,   91,  695,  696,
      697,  695,  700,  683,    0,    0,  690,  709,  690,  692,
      694,  699,  701,  713,  722,  722,  736,  731,  722,    0,

      725,  731,  730,  737,    0,  742,  733,    0,  734,  740,
      733,  751,  739,  754,  758,  758,  745,  757,    0,  745,
      771,  771,  778,  765,  774,  773,    0,  777,  774,  781,
      775,    0,    0,  793,  795,  794,  799,  782,    0,  799,
      799,  792,  793,  806,  799,  811,  815,    0,  816,  816,
      815,  809,    0,  821,  823,  822,  820,    0,  829,  829,
      838,  826,  840,  837,  849,  835,  839,  835,  853,  852,
      840,  843,    0,  847,  847,  858,    0,    0,  855,    0,
      855,  848,  855,  874,    0,    0,  870,  875,    0,  871,
      878,  886,  876,  883,  878,    0,    0,    0,    0,  887,

      882,  891,  891,    0,    0,    0,  904,  889,    0,    0,
        0,  909,  903,    0,    0,  905,    0,  901,    0,  917,
        0,  907,  903,  906,  911,  923,  918,  926,  931,    0,
        0,  919,  933,    0,    0,    0,  936,  930,  930,    0,
        0,    0,  927,    0,  933,    0, 1087, 1004, 1011, 1018,
     1025, 1032, 1039, 1041, 1048, 1055, 1062, 1069, 1076,   82,
     1080
    } ;

static yyconst flex_int16_t yy_def[462] =
    {   0,
      447,    1,  448,  448,  449,  449,  450,  450,  451,  451,
      452,  452,  447,  447,  447,  447,  447,  447,  447,  447,
      453,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  455,  447,  456,  457,  447,  447,  447,
      458,  447,  447,  447,  459,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  454,  454,  454,  454,

      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  447,  455,  456,  456,  447,  456,  457,   70,  447,
      457,  457,  457,  457,  457,  457,  457,  458,   72,  458,
      458,  458,  458,  458,  458,  458,  459,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  460,  447,  447,  447,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,

      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      447,  447,  447,  447,  461,  447,  447,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  447,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,

      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,

      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,    0,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447
    } ;

static yyconst flex_uint16_t yy_nxt[1171] =
    {   0,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   30,   30,   30,
       30,   30,   30,   31,   32,   33,   34,   35,   14,   36,
       37,   38,   39,   40,   41,   42,   43,   44,   45,   45,
       46,   47,   45,   48,   49,   45,   50,   51,   52,   45,
       53,   45,   45,   54,   55,   56,   57,   36,   37,   38,
       39,   40,   41,   42,   43,   44,   45,   46,   47,   45,
       48,   49,   45,   50,   51,   52,   45,   53,   45,   45,
       58,   59,   60,   65,   65,   68,   75,  225,   68,   61,
       69,   66,   66,   69,   61,   61,   75,   75,  158,  158,

       61,   77,   78,   79,   77,   77,   77,   77,   83,  100,
       84,   84,   84,   84,   84,   84,   84,   85,   91,  116,
      105,   92,   86,   88,  121,   89,   89,   89,   89,   89,
       89,   89,   94,  158,   95,   98,  100,   70,  114,   80,
       70,   72,   90,  115,  101,  117,  116,   72,  105,  177,
      158,  121,   99,  118,  158,  102,  119,  158,  103,  125,
      122,   87,  120,   98,  104,  106,  114,  107,  158,  108,
       90,  115,  101,  117,  109,  111,  177,  123,  110,   99,
      124,  118,  102,  112,  119,  103,  129,  125,  122,  120,
      178,  104,  179,  106,  107,  113,  108,  184,  126,  158,

      185,  109,  127,  111,  123,  110,  128,  124,  130,  190,
      135,  112,  131,  158,  129,  136,  191,  178,  447,  179,
      158,  158,  113,  447,  137,  184,  126,  185,  135,  158,
      127,  158,  137,  447,  128,  194,  130,  190,  158,  221,
      131,  140,  137,  192,  191,  158,  138,  159,  159,  159,
      159,  159,  159,  159,  160,  160,  160,  160,  160,  160,
      160,  188,  186,  194,  189,  158,  187,  138,  141,  142,
      192,  193,  195,  143,  161,  161,  161,  161,  162,  159,
      159,  144,  198,  199,  200,  145,  201,  146,  188,  147,
      186,  189,  149,  138,  187,  149,  141,  142,  193,  195,

      149,  143,  149,  149,  196,  149,  202,  203,  144,  198,
      199,  200,  145,  201,  146,  197,  147,  148,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,  196,  202,  203,  174,  149,  204,  148,  150,
      151,  205,  197,   88,  152,   89,   89,   89,   89,   89,
       89,   89,  153,  206,  207,  208,  154,  149,  155,  215,
      156,  139,   90,  174,  148,  204,  211,  150,  151,  205,
      139,  139,  152,  139,  139,  180,  229,  181,  212,  153,
      206,  207,  208,  154,  213,  155,  215,  156,  163,  209,
       90,  182,  183,  214,  211,  210,  139,  164,  164,  164,

      165,  165,  165,  180,  229,  181,  212,  216,  231,  163,
      166,  167,  213,  217,  218,  168,  232,  209,  182,  183,
      214,  219,  210,  169,  220,  228,  230,  170,  447,  171,
      139,  172,  173,  447,  216,  163,  231,  447,  166,  167,
      217,  218,  137,  168,  232,  235,  236,  244,  219,  139,
      169,  220,  228,  230,  170,  175,  171,  175,  172,  173,
      176,  176,  176,  176,  176,  176,  176,  158,  158,  239,
      240,  243,  235,  236,  158,  244,  159,  159,  159,  159,
      159,  159,  159,  222,  222,  222,  222,  222,  222,  222,
      158,  245,   73,  149,  139,  158,  239,  240,  243,  222,

      222,  222,  222,  222,  223,  223,  223,  223,  223,  223,
      158,  176,  176,  176,  176,  176,  176,  176,  245,  224,
      224,  224,  224,  224,  224,  226,  250,  226,  248,  132,
      227,  227,  227,  227,  227,  227,  227,  176,  176,  176,
      176,  176,  176,  176,  233,  237,  241,  246,  249,  251,
      234,  252,  253,  250,  238,  254,  248,  247,  255,  256,
       96,  257,  258,  242,  259,  260,   93,  261,  262,  263,
       82,  264,  233,  237,  241,  246,  249,  251,  234,  252,
      253,  238,  268,  254,  247,  255,  269,  256,  257,  258,
      242,  259,  270,  260,  261,  262,  271,  263,  264,  265,

      266,  272,  273,  276,  267,  158,  274,  275,  277,  268,
       81,   74,   73,  269,  224,  224,  224,  224,  224,  224,
      270,  447,   63,  280,  271,  279,  281,  265,  266,  272,
      273,  276,  267,  274,  275,  282,  277,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  280,  279,  283,  281,  284,  285,  286,   63,  287,
      288,  289,  291,  282,  290,  292,  293,  294,  295,  447,
      296,  297,  298,  447,  299,  300,  301,  447,  302,  303,
      283,  304,  305,  284,  285,  286,  287,  288,  306,  289,
      291,  290,  292,  293,  294,  307,  295,  296,  297,  308,

      298,  299,  300,  309,  301,  302,  310,  303,  304,  311,
      305,  312,  313,  314,  316,  306,  315,  317,  318,  319,
      320,  321,  322,  307,  323,  324,  325,  308,  326,  327,
      309,  328,  329,  332,  310,  333,  334,  311,  330,  312,
      313,  314,  316,  315,  317,  318,  319,  320,  335,  321,
      322,  336,  323,  324,  325,  331,  326,  327,  328,  329,
      332,  337,  333,  334,  338,  339,  330,  340,  341,  447,
      342,  343,  344,  345,  346,  335,  347,  350,  336,  348,
      349,  351,  331,  352,  447,  353,  354,  355,  337,  356,
      358,  338,  339,  357,  359,  340,  341,  342,  343,  344,

      345,  360,  346,  361,  347,  350,  348,  349,  351,  362,
      366,  352,  353,  363,  354,  355,  364,  356,  358,  365,
      357,  359,  367,  368,  369,  370,  371,  372,  373,  360,
      374,  361,  375,  376,  447,  377,  378,  362,  366,  379,
      363,  380,  381,  364,  382,  383,  365,  384,  385,  367,
      368,  369,  386,  370,  371,  372,  373,  374,  387,  391,
      375,  376,  377,  378,  388,  389,  390,  379,  380,  392,
      381,  393,  382,  383,  394,  384,  385,  395,  397,  386,
      396,  398,  399,  400,  401,  402,  387,  391,  403,  404,
      405,  388,  389,  390,  406,  407,  392,  408,  409,  393,

      410,  394,  411,  412,  414,  395,  397,  396,  398,  399,
      400,  413,  401,  402,  415,  403,  404,  405,  416,  417,
      421,  406,  418,  407,  408,  409,  419,  410,  420,  411,
      422,  412,  414,  423,  424,  425,  447,  426,  413,  427,
      428,  415,  429,  447,  430,  416,  431,  417,  421,  418,
      432,  433,  434,  419,  435,  420,  436,  422,  437,  438,
      423,  424,  439,  425,  426,  440,  441,  427,  428,  442,
      429,  430,  443,  444,  431,  445,  446,  432,  433,  434,
      447,  435,  447,  447,  436,  437,  447,  438,  447,  447,
      439,  447,  440,  447,  441,  447,  447,  442,  447,  443,

      444,  447,  445,  446,   61,   61,   61,   61,   61,   61,
       61,   62,   62,   62,   62,   62,   62,   62,   64,   64,
       64,   64,   64,   64,   64,   67,   67,   67,   67,   67,
       67,   67,   71,   71,   71,   71,   71,   71,   71,   76,
      447,   76,  447,   76,   76,   76,   97,   97,  133,  447,
      133,  133,  447,  133,  133,  134,  447,  134,  134,  134,
      134,  134,  138,  447,  138,  447,  138,  138,  138,  148,
      447,  148,  447,  148,  148,  148,  157,  447,  447,  157,
      157,  157,  157,  278,  447,  278,   13,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,

      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447
    } ;

static yyconst flex_int16_t yy_chk[1171] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    7,    8,    9,   18,  460,   10,   11,
        9,    7,    8,   10,   11,   12,   18,   18,  278,  225,

       12,   21,   21,   21,   21,   21,   21,   21,   28,   37,
       28,   28,   28,   28,   28,   28,   28,   29,   31,   44,
       39,   31,   29,   30,   48,   30,   30,   30,   30,   30,
       30,   30,   34,  224,   34,   36,   37,    9,   42,   21,
       10,   11,   30,   43,   38,   46,   44,   12,   39,   98,
      222,   48,   36,   46,  172,   38,   47,  171,   38,   50,
       49,   29,   47,   36,   38,   40,   42,   40,  170,   40,
       30,   43,   38,   46,   40,   41,   98,   49,   40,   36,
       49,   46,   38,   41,   47,   38,   52,   50,   49,   47,
       99,   38,  100,   40,   40,   41,   40,  102,   51,  169,

      103,   40,   51,   41,   49,   40,   51,   49,   53,  106,
       66,   41,   53,  168,   52,   66,  107,   99,  134,  100,
      167,  166,   41,  134,   66,  102,   51,  103,  135,  163,
       51,  159,  134,  135,   51,  110,   53,  106,   77,  157,
       53,   70,  135,  108,  107,   78,   70,   77,   77,   77,
       77,   77,   77,   77,   78,   78,   78,   78,   78,   78,
       78,  105,  104,  110,  105,   79,  104,   70,   70,   70,
      108,  109,  111,   70,   79,   79,   79,   79,   79,   79,
       79,   70,  113,  114,  115,   70,  116,   70,  105,   70,
      104,  105,  156,   70,  104,  155,   70,   70,  109,  111,

      154,   70,  153,  152,  112,  151,  117,  118,   70,  113,
      114,  115,   70,  116,   70,  112,   70,   72,   84,   84,
       84,   84,   84,   84,   84,   88,   88,   88,   88,   88,
       88,   88,  112,  117,  118,   84,  150,  119,   72,   72,
       72,  120,  112,   89,   72,   89,   89,   89,   89,   89,
       89,   89,   72,  121,  122,  122,   72,  148,   72,  126,
       72,  147,   89,   84,   72,  119,  124,   72,   72,  120,
      146,  145,   72,  144,  143,  101,  178,  101,  125,   72,
      121,  122,  122,   72,  125,   72,  126,   72,   80,  123,
       89,  101,  101,  125,  124,  123,  142,   80,   80,   80,

       80,   80,   80,  101,  178,  101,  125,  127,  180,   80,
       80,   80,  125,  128,  129,   80,  181,  123,  101,  101,
      125,  130,  123,   80,  131,  177,  179,   80,  137,   80,
      141,   80,   80,  137,  127,   80,  180,  139,   80,   80,
      128,  129,  137,   80,  181,  183,  184,  190,  130,  138,
       80,  131,  177,  179,   80,   90,   80,   90,   80,   80,
       90,   90,   90,   90,   90,   90,   90,  160,   76,  186,
      187,  189,  183,  184,  161,  190,  160,  160,  160,  160,
      160,  160,  160,  161,  161,  161,  161,  161,  161,  161,
      162,  191,   73,   71,   67,  164,  186,  187,  189,  162,

      162,  162,  162,  162,  164,  164,  164,  164,  164,  164,
      165,  175,  175,  175,  175,  175,  175,  175,  191,  165,
      165,  165,  165,  165,  165,  174,  195,  174,  193,   55,
      174,  174,  174,  174,  174,  174,  174,  176,  176,  176,
      176,  176,  176,  176,  182,  185,  188,  192,  194,  196,
      182,  197,  198,  195,  185,  199,  193,  192,  200,  201,
       35,  202,  203,  188,  204,  205,   33,  206,  207,  208,
       27,  209,  182,  185,  188,  192,  194,  196,  182,  197,
      198,  185,  211,  199,  192,  200,  212,  201,  202,  203,
      188,  204,  213,  205,  206,  207,  214,  208,  209,  210,

      210,  215,  216,  219,  210,  223,  217,  218,  220,  211,
       24,   17,   15,  212,  223,  223,  223,  223,  223,  223,
      213,   13,    6,  229,  214,  228,  230,  210,  210,  215,
      216,  219,  210,  217,  218,  231,  220,  226,  226,  226,
      226,  226,  226,  226,  227,  227,  227,  227,  227,  227,
      227,  229,  228,  232,  230,  233,  234,  236,    5,  237,
      238,  239,  241,  231,  240,  242,  243,  244,  245,    0,
      246,  247,  248,    0,  249,  250,  251,    0,  252,  253,
      232,  254,  255,  233,  234,  236,  237,  238,  256,  239,
      241,  240,  242,  243,  244,  257,  245,  246,  247,  258,

      248,  249,  250,  259,  251,  252,  260,  253,  254,  262,
      255,  264,  265,  266,  268,  256,  267,  270,  271,  272,
      273,  276,  277,  257,  279,  280,  281,  258,  282,  283,
      259,  284,  287,  289,  260,  290,  291,  262,  288,  264,
      265,  266,  268,  267,  270,  271,  272,  273,  292,  276,
      277,  293,  279,  280,  281,  288,  282,  283,  284,  287,
      289,  294,  290,  291,  295,  296,  288,  297,  298,    0,
      299,  301,  302,  303,  304,  292,  306,  310,  293,  307,
      309,  311,  288,  312,    0,  313,  314,  315,  294,  316,
      318,  295,  296,  317,  320,  297,  298,  299,  301,  302,

      303,  321,  304,  322,  306,  310,  307,  309,  311,  323,
      328,  312,  313,  324,  314,  315,  325,  316,  318,  326,
      317,  320,  329,  330,  331,  334,  335,  336,  337,  321,
      338,  322,  340,  341,    0,  342,  343,  323,  328,  344,
      324,  345,  346,  325,  347,  349,  326,  350,  351,  329,
      330,  331,  352,  334,  335,  336,  337,  338,  354,  359,
      340,  341,  342,  343,  355,  356,  357,  344,  345,  360,
      346,  361,  347,  349,  362,  350,  351,  363,  365,  352,
      364,  366,  367,  368,  369,  370,  354,  359,  371,  372,
      374,  355,  356,  357,  375,  376,  360,  379,  381,  361,

      382,  362,  383,  384,  388,  363,  365,  364,  366,  367,
      368,  387,  369,  370,  390,  371,  372,  374,  391,  392,
      400,  375,  393,  376,  379,  381,  394,  382,  395,  383,
      401,  384,  388,  402,  403,  407,    0,  408,  387,  412,
      413,  390,  416,    0,  418,  391,  420,  392,  400,  393,
      422,  423,  424,  394,  425,  395,  426,  401,  427,  428,
      402,  403,  429,  407,  408,  432,  433,  412,  413,  437,
      416,  418,  438,  439,  420,  443,  445,  422,  423,  424,
        0,  425,    0,    0,  426,  427,    0,  428,    0,    0,
      429,    0,  432,    0,  433,    0,    0,  437,    0,  438,

      439,    0,  443,  445,  448,  448,  448,  448,  448,  448,
      448,  449,  449,  449,  449,  449,  449,  449,  450,  450,
      450,  450,  450,  450,  450,  451,  451,  451,  451,  451,
      451,  451,  452,  452,  452,  452,  452,  452,  452,  453,
        0,  453,    0,  453,  453,  453,  454,  454,  455,    0,
      455,  455,    0,  455,  455,  456,    0,  456,  456,  456,
      456,  456,  457,    0,  457,    0,  457,  457,  457,  458,
        0,  458,    0,  458,  458,  458,  459,    0,    0,  459,
      459,  459,  459,  461,    0,  461,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,

      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "stupido.l"
/*Ejecutado con flex -i (para minusculas y mayusculas)*/





#line 9 "stupido.l"
   #include "stupido.tab.h"
   #include <string.h>
   #include <stdlib.h>
   #include <stdio.h>
   int lineas = 1;
#line 887 "lex.yy.c"

#define INITIAL 0
#define caracter 1
#define comentariocorto 2
#define comentlargo 3
#define cadena 4
#define sigue 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 55 "stupido.l"


#line 1113 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 448 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1087 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 57 "stupido.l"
BEGIN(comentariocorto);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 58 "stupido.l"
;
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 59 "stupido.l"
BEGIN(INITIAL);lineas++;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 62 "stupido.l"
BEGIN(cadena);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 63 "stupido.l"
printf("linea %d, cadena: %s\n",lineas,yytext);			return(CTC_CADENA);
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 64 "stupido.l"
lineas++;BEGIN(sigue);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 65 "stupido.l"
BEGIN(INITIAL);
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 66 "stupido.l"
printf("linea %d, error en la cadena \n",lineas);BEGIN(INITIAL);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 67 "stupido.l"
printf("linea %d, sigue la cadena: %s\n",lineas,yytext);BEGIN(cadena);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 74 "stupido.l"
BEGIN(comentlargo);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 75 "stupido.l"
;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 76 "stupido.l"
;
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 77 "stupido.l"
lineas++;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 78 "stupido.l"
BEGIN(INITIAL);
	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 82 "stupido.l"
lineas++; 
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 83 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(CLASE);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 84 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(CARACTER);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 85 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(CASO);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 86 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(CADENA);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 87 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(BOOLEANO);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 88 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(ASOCIATIVA);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 89 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(ABSTRACTO);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 90 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(CABECERA);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 91 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(CONJUNTO);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 92 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(CONSTANTE);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 93 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(CUERPO);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 94 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(CONSTRUCTOR);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 95 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(CUANDO);
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 96 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(DESCENDENTE);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 97 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(DESTRUCTOR);
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 98 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(DE);
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 99 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(DEVOLVER);
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 100 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(CARGA);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 101 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(ELEMENTO);
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 102 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(EJECUTA);
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 103 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(EN);
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 104 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(ENTERO);
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 105 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(ENTONCES);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 106 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(ES);
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 107 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(ESPECIFICO);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 108 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(EXCEPTO);
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 109 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(FICHERO);
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 110 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	;return(FINAL);
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 111 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(FINALMENTE);
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 112 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(FUNCION);
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 113 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	;return(GENERICO);
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 114 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(HASTA);
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 115 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(INTERFAZ);
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 116 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(LANZAR);
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 117 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(LISTA);
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 118 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(MIENTRAS);
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 119 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(MODIFICABLE);
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 120 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(OTRO);
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 121 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(PAQUETE);
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 122 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(PARA);
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 123 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(PRIVADO);
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 124 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(PROBAR);
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 125 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(PROCEDIMIENTO);
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 126 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(PROGRAMA);
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 127 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(PUBLICO);
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 128 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(REAL);
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 129 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(REGISTRO);
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 130 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(REPITE);
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 131 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(SALIR);
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 132 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(SEMIPUBLICO);
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 133 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(SI);
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 134 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(SINO);
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 135 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(TIPO);
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 136 "stupido.l"
printf("linea %d, palabra reservada: %s\n",lineas,yytext);	return(VARIABLE);
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 137 "stupido.l"
printf("linea %d, delimitador: %s\n",lineas,yytext);		return(CUATRO_PTOS);
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 138 "stupido.l"
printf("linea %d, delimitador: %s\n",lineas,yytext);		return(DOS_PTOS);
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 139 "stupido.l"
printf("linea %d, caracter: %s\n",lineas,yytext);		return(CTC_CARACTER);
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 140 "stupido.l"
printf("linea %d, constante_booleana: %s\n",lineas,yytext);	return(CTC_BOOLEANA);
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 141 "stupido.l"
printf("linea %d, constante_booleana: %s\n",lineas,yytext);	return(CTC_BOOLEANA);
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 142 "stupido.l"
printf("linea %d, operador relacional: %s\n",lineas,yytext);	return(EQ);
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 143 "stupido.l"
printf("linea %d, operador relacional: %s\n",lineas,yytext);	return(GEQ);
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 144 "stupido.l"
printf("linea %d, operador relacional: %s\n",lineas,yytext);	return(LEQ);
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 145 "stupido.l"
printf("linea %d, operador relacional: %s\n",lineas,yytext);	return(NEQ);
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 146 "stupido.l"
printf("linea %d, operador aritmetico: %s\n",lineas,yytext);	return(POTENCIA);
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 147 "stupido.l"
printf("linea %d, operador de bits: %s\n",lineas,yytext);	return(DESPD);
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 148 "stupido.l"
printf("linea %d, operador de bits: %s\n",lineas,yytext);	return(DESPI);
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 149 "stupido.l"
printf("linea %d, delimitador: %s\n",lineas,yytext);		return(FLECHA_DOBLE);
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 150 "stupido.l"
printf("linea %d, operador logico: %s\n",lineas,yytext);	return(OR);
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 151 "stupido.l"
printf("linea %d, operador logico: %s\n",lineas,yytext);	return(AND);
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 152 "stupido.l"
printf("linea %d, IDENTIFICADOR: %s\n",lineas,yytext);		return(IDENTIFICADOR);
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 153 "stupido.l"
printf("linea %d, constante entera: %s\n",lineas,yytext);	return(CTC_ENTERA);
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 154 "stupido.l"
printf("linea %d, constante real: %s\n",lineas,yytext);		return(CTC_REAL);
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 155 "stupido.l"
printf("linea %d, PATH: %s\n",lineas,yytext);			return(PATH);
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 156 "stupido.l"
printf("linea %d, delimitador: %s\n",lineas,yytext);		return(yytext[0]);
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 157 "stupido.l"
printf("linea %d, delimitador: %s\n",lineas,yytext);		return(yytext[0]);
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 158 "stupido.l"
printf("linea %d, operador asignacion: %s\n",lineas,yytext);	return(yytext[0]);
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 159 "stupido.l"
printf("linea %d, delimitador: %s\n",lineas,yytext);		return(yytext[0]);
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 160 "stupido.l"
printf("linea %d, delimitador: %s\n",lineas,yytext);		return(yytext[0]);
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 161 "stupido.l"
printf("linea %d, delimitador: %s\n",lineas,yytext);		return(yytext[0]);
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 162 "stupido.l"
printf("linea %d, memoria: %s\n",lineas,yytext);		return(yytext[0]);
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 163 "stupido.l"
printf("linea %d, memoria: %s\n",lineas,yytext);		return(yytext[0]);
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 164 "stupido.l"
printf("linea %d, delimitador: %s\n",lineas,yytext);		return(yytext[0]);
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 165 "stupido.l"
printf("linea %d, delimitador: %s\n",lineas,yytext);		return(yytext[0]);
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 166 "stupido.l"
printf("linea %d, delimitador: %s\n",lineas,yytext);		return(yytext[0]);
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 167 "stupido.l"
printf("linea %d, operador aritmético: %s\n",lineas,yytext);	return(yytext[0]);
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 168 "stupido.l"
printf("linea %d, operador aritmético: %s\n",lineas,yytext);	return(yytext[0]);
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 169 "stupido.l"
printf("linea %d, operador aritmético: %s\n",lineas,yytext);	return(yytext[0]);
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 170 "stupido.l"
printf("linea %d, operador de bits: %s\n",lineas,yytext);	return(yytext[0]);
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 171 "stupido.l"
printf("linea %d, operador de bits: %s\n",lineas,yytext);	return(yytext[0]);
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 172 "stupido.l"
printf("linea %d, operador aritmético: %s\n",lineas,yytext);	return(yytext[0]);
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 173 "stupido.l"
printf("linea %d, operador lógico: %s\n",lineas,yytext);	return(yytext[0]);
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 174 "stupido.l"
printf("linea %d, operador relacional: %s\n",lineas,yytext);	return(yytext[0]);
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 175 "stupido.l"
printf("linea %d, operador relacional: %s\n",lineas,yytext);	return(yytext[0]);
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 176 "stupido.l"
printf("linea %d, operador memoria: %s\n",lineas,yytext);	return(yytext[0]);
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 177 "stupido.l"
printf("linea %d, operador aritmético: %s\n",lineas,yytext);	return(yytext[0]);
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 178 "stupido.l"
;
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 180 "stupido.l"
printf("linea %d,ERROR: %s\n",lineas,yytext);
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 182 "stupido.l"
ECHO;
	YY_BREAK
#line 1740 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(caracter):
case YY_STATE_EOF(comentariocorto):
case YY_STATE_EOF(comentlargo):
case YY_STATE_EOF(cadena):
case YY_STATE_EOF(sigue):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 448 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 448 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 447);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 182 "stupido.l"






